"""empty message

Revision ID: 12ca255b3992
Revises: 1fbc49e9ca5a
Create Date: 2022-06-26 23:38:30.280073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ca255b3992'
down_revision = '1fbc49e9ca5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('fileId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('fileName', sa.String(length=320), nullable=True),
    sa.Column('fileBytes', sa.Integer(), nullable=True),
    sa.Column('fileType', sa.String(length=320), nullable=True),
    sa.Column('fileWidth', sa.Integer(), nullable=True),
    sa.Column('fileHeight', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fileId')
    )
    op.create_index(op.f('ix_files_dateCreated'), 'files', ['dateCreated'], unique=False)
    op.create_index(op.f('ix_files_dateUpdated'), 'files', ['dateUpdated'], unique=False)
    op.create_index(op.f('ix_files_fileBytes'), 'files', ['fileBytes'], unique=False)
    op.create_index(op.f('ix_files_fileHeight'), 'files', ['fileHeight'], unique=False)
    op.create_index(op.f('ix_files_fileName'), 'files', ['fileName'], unique=False)
    op.create_index(op.f('ix_files_fileType'), 'files', ['fileType'], unique=False)
    op.create_index(op.f('ix_files_fileWidth'), 'files', ['fileWidth'], unique=False)
    op.create_index(op.f('ix_files_tag'), 'files', ['tag'], unique=False)
    op.create_index(op.f('ix_files_userId'), 'files', ['userId'], unique=False)
    op.create_table('plan',
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('storageSize', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Integer(), nullable=True),
    sa.Column('subdomains', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateExpired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('planId')
    )
    op.create_index(op.f('ix_plan_dateCreated'), 'plan', ['dateCreated'], unique=False)
    op.create_index(op.f('ix_plan_dateExpired'), 'plan', ['dateExpired'], unique=False)
    op.create_index(op.f('ix_plan_storageSize'), 'plan', ['storageSize'], unique=False)
    op.create_index(op.f('ix_plan_subdomains'), 'plan', ['subdomains'], unique=False)
    op.create_index(op.f('ix_plan_tags'), 'plan', ['tags'], unique=False)
    op.create_index(op.f('ix_plan_userId'), 'plan', ['userId'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=True),
    sa.Column('subdomain', sa.String(length=255), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateUpdated', sa.DateTime(), nullable=True),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_dateCreated'), 'users', ['dateCreated'], unique=False)
    op.create_index(op.f('ix_users_dateUpdated'), 'users', ['dateUpdated'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_index(op.f('ix_users_subdomain'), 'users', ['subdomain'], unique=False)
    op.create_index(op.f('ix_users_totalSize'), 'users', ['totalSize'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_totalSize'), table_name='users')
    op.drop_index(op.f('ix_users_subdomain'), table_name='users')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dateUpdated'), table_name='users')
    op.drop_index(op.f('ix_users_dateCreated'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plan_userId'), table_name='plan')
    op.drop_index(op.f('ix_plan_tags'), table_name='plan')
    op.drop_index(op.f('ix_plan_subdomains'), table_name='plan')
    op.drop_index(op.f('ix_plan_storageSize'), table_name='plan')
    op.drop_index(op.f('ix_plan_dateExpired'), table_name='plan')
    op.drop_index(op.f('ix_plan_dateCreated'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_files_userId'), table_name='files')
    op.drop_index(op.f('ix_files_tag'), table_name='files')
    op.drop_index(op.f('ix_files_fileWidth'), table_name='files')
    op.drop_index(op.f('ix_files_fileType'), table_name='files')
    op.drop_index(op.f('ix_files_fileName'), table_name='files')
    op.drop_index(op.f('ix_files_fileHeight'), table_name='files')
    op.drop_index(op.f('ix_files_fileBytes'), table_name='files')
    op.drop_index(op.f('ix_files_dateUpdated'), table_name='files')
    op.drop_index(op.f('ix_files_dateCreated'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
