"""subdomains

Revision ID: 13bc49f84ebe
Revises: ac1c97afe9cd
Create Date: 2022-05-09 07:48:42.929245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bc49f84ebe'
down_revision = 'ac1c97afe9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('tag', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_files_tag'), 'files', ['tag'], unique=False)
    op.add_column('users', sa.Column('subdomain', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_customTag', table_name='users')
    op.create_index(op.f('ix_users_subdomain'), 'users', ['subdomain'], unique=False)
    op.drop_column('users', 'customTag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customTag', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_subdomain'), table_name='users')
    op.create_index('ix_users_customTag', 'users', ['customTag'], unique=False)
    op.drop_column('users', 'subdomain')
    op.drop_index(op.f('ix_files_tag'), table_name='files')
    op.drop_column('files', 'tag')
    # ### end Alembic commands ###
