"""empty message

Revision ID: 1bbabc3dcf50
Revises: f9ed83ee9b17
Create Date: 2022-05-20 22:08:11.636534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbabc3dcf50'
down_revision = 'f9ed83ee9b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verificationCode', table_name='users')
    op.drop_column('users', 'verificationCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verificationCode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_verificationCode', 'users', ['verificationCode'], unique=False)
    # ### end Alembic commands ###
