"""empty message

Revision ID: 1fbc49e9ca5a
Revises: 1bbabc3dcf50
Create Date: 2022-06-26 22:43:45.538885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbc49e9ca5a'
down_revision = '1bbabc3dcf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('planId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('storageSize', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Integer(), nullable=True),
    sa.Column('subdomains', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateExpired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('planId')
    )
    op.create_index(op.f('ix_plan_dateCreated'), 'plan', ['dateCreated'], unique=False)
    op.create_index(op.f('ix_plan_dateExpired'), 'plan', ['dateExpired'], unique=False)
    op.create_index(op.f('ix_plan_storageSize'), 'plan', ['storageSize'], unique=False)
    op.create_index(op.f('ix_plan_subdomains'), 'plan', ['subdomains'], unique=False)
    op.create_index(op.f('ix_plan_tags'), 'plan', ['tags'], unique=False)
    op.create_index(op.f('ix_plan_userId'), 'plan', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_userId'), table_name='plan')
    op.drop_index(op.f('ix_plan_tags'), table_name='plan')
    op.drop_index(op.f('ix_plan_subdomains'), table_name='plan')
    op.drop_index(op.f('ix_plan_storageSize'), table_name='plan')
    op.drop_index(op.f('ix_plan_dateExpired'), table_name='plan')
    op.drop_index(op.f('ix_plan_dateCreated'), table_name='plan')
    op.drop_table('plan')
    # ### end Alembic commands ###
