"""initial migration

Revision ID: 21ef654af5bf
Revises: 
Create Date: 2022-03-28 19:11:13.147956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ef654af5bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('fileBytes', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('fileType', sa.String(length=320), nullable=True))
    op.add_column('files', sa.Column('fileWidth', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('fileHeight', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_files_fileBytes'), 'files', ['fileBytes'], unique=False)
    op.create_index(op.f('ix_files_fileHeight'), 'files', ['fileHeight'], unique=False)
    op.create_index(op.f('ix_files_fileType'), 'files', ['fileType'], unique=False)
    op.create_index(op.f('ix_files_fileWidth'), 'files', ['fileWidth'], unique=False)
    op.create_index(op.f('ix_files_userId'), 'files', ['userId'], unique=False)
    op.create_index(op.f('ix_users_dateCreated'), 'users', ['dateCreated'], unique=False)
    op.create_index(op.f('ix_users_dateUpdated'), 'users', ['dateUpdated'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dateUpdated'), table_name='users')
    op.drop_index(op.f('ix_users_dateCreated'), table_name='users')
    op.drop_index(op.f('ix_files_userId'), table_name='files')
    op.drop_index(op.f('ix_files_fileWidth'), table_name='files')
    op.drop_index(op.f('ix_files_fileType'), table_name='files')
    op.drop_index(op.f('ix_files_fileHeight'), table_name='files')
    op.drop_index(op.f('ix_files_fileBytes'), table_name='files')
    op.drop_column('files', 'fileHeight')
    op.drop_column('files', 'fileWidth')
    op.drop_column('files', 'fileType')
    op.drop_column('files', 'fileBytes')
    # ### end Alembic commands ###
