"""naming convention change to customTag

Revision ID: 2e0600ea20c0
Revises: 55b7148b84a1
Create Date: 2022-03-29 21:38:10.517594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0600ea20c0'
down_revision = '55b7148b84a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customTag', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_customUrl', table_name='users')
    op.create_index(op.f('ix_users_customTag'), 'users', ['customTag'], unique=False)
    op.drop_column('users', 'customUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customUrl', sa.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_users_customTag'), table_name='users')
    op.create_index('ix_users_customUrl', 'users', ['customUrl'], unique=False)
    op.drop_column('users', 'customTag')
    # ### end Alembic commands ###
