"""custom urls in user

Revision ID: 55b7148b84a1
Revises: 21ef654af5bf
Create Date: 2022-03-29 20:58:03.023435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b7148b84a1'
down_revision = '21ef654af5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customUrl', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_customUrl'), 'users', ['customUrl'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_customUrl'), table_name='users')
    op.drop_column('users', 'customUrl')
    # ### end Alembic commands ###
