"""total bytes

Revision ID: ac1c97afe9cd
Revises: 4e1378c97a67
Create Date: 2022-03-30 22:24:44.431802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1c97afe9cd'
down_revision = '4e1378c97a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totalSize', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_totalSize'), 'users', ['totalSize'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_totalSize'), table_name='users')
    op.drop_column('users', 'totalSize')
    # ### end Alembic commands ###
