"""empty message

Revision ID: bbff74772528
Revises: 12ca255b3992
Create Date: 2022-06-27 00:04:47.171031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbff74772528'
down_revision = '12ca255b3992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('ID', sa.Integer(), nullable=False))
    op.alter_column('plan', 'planId',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('nextval(\'"plan_planId_seq"\'::regclass)'))
    op.create_index(op.f('ix_plan_planId'), 'plan', ['planId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_planId'), table_name='plan')
    op.alter_column('plan', 'planId',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('nextval(\'"plan_planId_seq"\'::regclass)'))
    op.drop_column('plan', 'ID')
    # ### end Alembic commands ###
