"""empty message

Revision ID: cb91d36f4c3e
Revises: cff7a1ee5b19
Create Date: 2022-05-17 22:17:29.544106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb91d36f4c3e'
down_revision = 'cff7a1ee5b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verificationCode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_verificationCode'), 'users', ['verificationCode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verificationCode'), table_name='users')
    op.drop_column('users', 'verificationCode')
    # ### end Alembic commands ###
