"""verification code

Revision ID: cff7a1ee5b19
Revises: 13bc49f84ebe
Create Date: 2022-05-17 21:50:46.688594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff7a1ee5b19'
down_revision = '13bc49f84ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verificationCode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_verificationCode'), 'users', ['verificationCode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verificationCode'), table_name='users')
    op.drop_column('users', 'verificationCode')
    # ### end Alembic commands ###
