"""empty message

Revision ID: d018ca8fc831
Revises: b89f991f998a
Create Date: 2022-06-27 13:51:34.449389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd018ca8fc831'
down_revision = 'b89f991f998a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('plan', 'ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"plan_ID_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('plan', 'id')
    # ### end Alembic commands ###
