"""empty message

Revision ID: f9ed83ee9b17
Revises: cb91d36f4c3e
Create Date: 2022-05-20 22:02:09.934408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ed83ee9b17'
down_revision = 'cb91d36f4c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verificationCode', table_name='users')
    op.drop_column('users', 'verificationCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verificationCode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_verificationCode', 'users', ['verificationCode'], unique=False)
    # ### end Alembic commands ###
